# Language/versions
language: node_js
node_js:
 - 0.9
 - 0.8
 - 0.6

# Install (quieten npm)
install: npm install --silent

# Build script
script: ./node_modules/.bin/jake ci

# Notifications
notifications:
  email: false
